declare const process: {
  env: {
    GOOGLE_CLOUD_API_KEY?: string;
    GEMINI_API_KEY?: string;
    NEXT_PUBLIC_FIREBASE_API_KEY?: string;
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN?: string;
    NEXT_PUBLIC_FIREBASE_PROJECT_ID?: string;
    NEXT_PUBLIC_FIREBASE_APP_ID?: string;
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID?: string;
    NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID?: string;
    GCLOUD_PROJECT?: string;
    DOCAI_PROCESSOR_ID?: string;
    DOCAI_LOCATION?: string;
    GOOGLE_CLOUD_CLIENT_EMAIL?: string;
    GOOGLE_CLOUD_PRIVATE_KEY?: string;
  };
};